name: Pack

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Commit Version
        run: |
          cd source
          sed "s/{commit}/`git rev-parse HEAD --short 7`/g" pack.mcmeta > pack.mcmeta.tmp && mv pack.mcmeta.tmp pack.mcmeta
          cd ../

      - name: Pack Source
        run: |
          cd source
          zip -9 -r ../GemPowered-Music.zip *
          cd ../

      - uses: actions/upload-artifact@v2
        name: Upload GemPowered-Music.zip
        with:
          name: GemPowered-Music.zip
          path: source/
