name: Pack

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set Commit Version
        run: |
          cd source
          sed "s/{commit}/`git rev-parse --short=7 HEAD`/g" pack.mcmeta > pack.mcmeta.tmp && mv pack.mcmeta.tmp pack.mcmeta
          cd ../

      - uses: actions/upload-artifact@v2
        name: Upload GemPowered-Music.zip
        with:
          name: GemPowered-Music
          path: source/
